### ISSUE TITLE
Can't create a policy that only affects egress, or only ingress

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/felix#1180]
Not sure if this is a Felix issue or a libcalico-go issue yet, but I can't seem to figure out how to create a policy which only affects egress.

I've created the following:

```
- apiVersion: v1
  kind: policy
  metadata:
    name: advanced-policy-demo.deny-egress
  spec:
    egress:
    - action: deny
      destination:
        selector: calico/k8s_ns != 'advanced-policy-demo'
      source:
        selector: calico/k8s_ns == 'advanced-policy-demo'
    order: 500
    selector: calico/k8s_ns == 'advanced-policy-demo'
```

It shows up in etcd like so:

```
{"order":500,"outbound_rules":[{"action":"deny","src_selector":"calico/k8s_ns == 'advanced-policy-demo'","dst_selector":"calico/k8s_ns != 'advanced-policy-demo'"}],"selector":"calico/k8s_ns == 'advanced-policy-demo'"}
```

The above policy is dropping ingress traffic to the selected workloadendpoints, even though there are other policies (at a lower order) which allow that traffic.

I would have thought that since no ingress rules are specified, then ingress would not be affected.

CC @robbrockbank @fasaxc

**Comment by caseydavenport** [comment]
Looks like felix is installing a rule to jump to the policy chain for ingress, even though no ingress exists

```
-A felix-to-297030229bb -m mark --mark 0x0/0x2000000 -j felix-p-_4c334da82b4ce35-i
```

but it's not populating that chain with anything, so the traffic just gets dropped.

I think we need a way of expressing to Felix that this policy is "egress only" or "ingress only".

**Comment by robbrockbank** [comment]
Just posting in the formatted JSON:

```
{  
   "order":500,
   "outbound_rules":[  
      {  
         "action":"deny",
         "src_selector":"calico/k8s_ns == 'advanced-policy-demo'",
         "dst_selector":"calico/k8s_ns != 'advanced-policy-demo'"
      }
   ],
   "selector":"calico/k8s_ns == 'advanced-policy-demo'"
}
```

**Comment by fasaxc** [comment]
This is WAD; few things interacting here:

- Felix doesn't distinguish between missing list of rules and empty list of rules.
- If no policies match an endpoint then packets skip to the next tier or to the list of profiles.
- If at least one policy matches, packets go through policies in order until they hit an allow or a pass instruction.
-  If at least one policy matches and a packet hits the end of the tier without hitting an allow or pass then they're dropped.

So, the problem is that by adding a single policy, you're now sending all packets through the tier.  Fix is to install a default policy to allow ingress traffic at the end of the tier so that your earlier policies can omit ingress rules and the packets will hit your pass/allow at the end of the tier.

**Comment by caseydavenport** [comment]
@fasaxc I should have made it more clear - I have created more than one policy.

I have another policy at a lower order that allows the traffic.  When I delete the policy above, the traffic is allowed.  When I add it back, the traffic is dropped.

I will reproduce and then post the full contents of the policy I've created.

**Comment by fasaxc** [comment]
@caseydavenport Now that might be a bug; if you have an earlier (or even a later) policy allowing the ingress traffic then that should do the trick.

**Comment by fasaxc** [comment]
> but it's not populating that chain with anything, so the traffic just gets dropped.
iptables default action on reaching the end of a chain is to `RETURN`, not `DROP`, so processing should continue with the next policy in the list.

**Comment by caseydavenport** [comment]
All policies I've created:

```
macncheese:vagrant casey$ calicoctl get policy -o yaml
- apiVersion: v1
  kind: policy
  metadata:
    name: advanced-policy-demo.access-nginx
  spec:
    egress:
    - action: allow
      destination: {}
      source: {}
    ingress:
    - action: allow
      destination: {}
      source:
        selector: calico/k8s_ns == 'advanced-policy-demo'
    order: 1000
    selector: calico/k8s_ns == 'advanced-policy-demo' && run == 'nginx'
- apiVersion: v1
  kind: policy
  metadata:
    name: advanced-policy-demo.deny-egress
  spec:
    egress:
    - action: deny
      destination:
        selector: calico/k8s_ns != 'advanced-policy-demo'
      source:
        selector: calico/k8s_ns == 'advanced-policy-demo'
    order: 500
    selector: calico/k8s_ns == 'advanced-policy-demo'
- apiVersion: v1
  kind: policy
  metadata:
    name: k8s-policy-no-match
  spec:
    egress:
    - action: pass
      destination: {}
      source: {}
    ingress:
    - action: pass
      destination: {}
      source: {}
    order: 2000
    selector: has(calico/k8s_ns)
```

All profiles I've created:

```
- apiVersion: v1
  kind: profile
  metadata:
    name: k8s_ns.advanced-policy-demo
    tags:
    - k8s_ns.advanced-policy-demo
  spec:
    egress:
    - action: allow
      destination: {}
      source: {}
    ingress:
    - action: allow
      destination: {}
      source: {}
- apiVersion: v1
  kind: profile
  metadata:
    name: k8s_ns.default
    tags:
    - k8s_ns.default
  spec:
    egress:
    - action: allow
      destination: {}
      source: {}
    ingress:
    - action: allow
      destination: {}
      source: {}
- apiVersion: v1
  kind: profile
  metadata:
    name: k8s_ns.kube-system
    tags:
    - k8s_ns.kube-system
  spec:
    egress:
    - action: allow
      destination: {}
      source: {}
    ingress:
    - action: allow
      destination: {}
      source: {}
```

Note that there is a backstop policy which defaults to "pass" so any traffic which hits the tier should be sent to profiles, which all "allow" ingress and egress.

When I remove the `advanced-policy-demo.deny-egress` policy then ingress traffic works, when I add it back it doesn't work.

It feels a lot like this is a bug.

**Comment by caseydavenport** [comment]
> If at least one policy matches, packets go through policies in order until they hit an allow or a pass instruction.

I think this is the behavior that isn't working.  The behavior I'm seeing:

"If at least one policy matches, packets go through policies in order until they hit an allow, pass, or deny action, or a policy with no rules, which is treated as a deny."

**Comment by caseydavenport** [comment]
```
:felix-from-91f18ff5595 - [0:0]
:felix-from-c1f72ae9871 - [0:0]
:felix-p-_0f05888047b5982-i - [0:0]
:felix-p-_0f05888047b5982-o - [0:0]
:felix-p-_258af862421b4a4-i - [0:0]
:felix-p-_258af862421b4a4-o - [0:0]
:felix-p-_43fdb4cd2c20923-i - [0:0]
:felix-p-_43fdb4cd2c20923-o - [0:0]
:felix-p-_4c334da82b4ce35-i - [0:0]
:felix-p-_4c334da82b4ce35-o - [0:0]
:felix-p-_722590149132d26-i - [0:0]
:felix-p-_722590149132d26-o - [0:0]
:felix-to-30b4541c7ef - [0:0]
:felix-to-91f18ff5595 - [0:0]
:felix-to-c1f72ae9871 - [0:0]
-A INPUT -j felix-INPUT
-A INPUT -j KUBE-FIREWALL
-A FORWARD -j felix-FORWARD
-A FORWARD -j DOCKER-ISOLATION
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A OUTPUT -j felix-OUTPUT
-A OUTPUT -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A OUTPUT -j KUBE-FIREWALL
-A DOCKER-ISOLATION -j RETURN
-A KUBE-FIREWALL -m comment --comment "kubernetes firewall for dropping marked packets" -m mark --mark 0x8000/0x8000 -j DROP
-A felix-FAILSAFE-IN -p tcp -m tcp --dport 22 -j ACCEPT
-A felix-FAILSAFE-OUT -p tcp -m tcp --dport 2379 -j ACCEPT
-A felix-FAILSAFE-OUT -p tcp -m tcp --dport 2380 -j ACCEPT
-A felix-FAILSAFE-OUT -p tcp -m tcp --dport 4001 -j ACCEPT
-A felix-FAILSAFE-OUT -p tcp -m tcp --dport 7001 -j ACCEPT
-A felix-FORWARD -i cali+ -m conntrack --ctstate INVALID -j DROP
-A felix-FORWARD -o cali+ -m conntrack --ctstate INVALID -j DROP
-A felix-FORWARD -i cali+ -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A felix-FORWARD -o cali+ -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A felix-FORWARD -i cali+ -j felix-FROM-ENDPOINT
-A felix-FORWARD -o cali+ -j felix-TO-ENDPOINT
-A felix-FORWARD -i cali+ -j ACCEPT
-A felix-FORWARD -o cali+ -j ACCEPT
-A felix-FROM-ENDPOINT -i cali91f18ff5595 -g felix-from-91f18ff5595
-A felix-FROM-ENDPOINT -i calic1f72ae9871 -g felix-from-c1f72ae9871
-A felix-FROM-ENDPOINT -i cali30b4541c7ef -g felix-from-30b4541c7ef
-A felix-FROM-ENDPOINT -m comment --comment "From unknown endpoint" -j DROP
-A felix-FROM-HOST-IF -m comment --comment "Unknown interface, return" -j RETURN
-A felix-INPUT -m conntrack --ctstate INVALID -j DROP
-A felix-INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A felix-INPUT -j MARK --set-xmark 0x0/0x4000000
-A felix-INPUT -i cali+ -j MARK --set-xmark 0x4000000/0x4000000
-A felix-INPUT -m mark --mark 0x0/0x4000000 -g felix-FROM-HOST-IF
-A felix-INPUT -p udp -m udp --sport 68 --dport 67 -j ACCEPT
-A felix-INPUT -p udp -m udp --dport 53 -j ACCEPT
-A felix-INPUT -j felix-FROM-ENDPOINT
-A felix-OUTPUT -m conntrack --ctstate INVALID -j DROP
-A felix-OUTPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A felix-OUTPUT -j MARK --set-xmark 0x0/0x4000000
-A felix-OUTPUT -o cali+ -j MARK --set-xmark 0x4000000/0x4000000
-A felix-OUTPUT -m mark --mark 0x0/0x4000000 -g felix-TO-HOST-IF
-A felix-TO-ENDPOINT -o cali91f18ff5595 -g felix-to-91f18ff5595
-A felix-TO-ENDPOINT -o calic1f72ae9871 -g felix-to-c1f72ae9871
-A felix-TO-ENDPOINT -o cali30b4541c7ef -g felix-to-30b4541c7ef
-A felix-TO-ENDPOINT -m comment --comment "To unknown endpoint" -j DROP
-A felix-TO-HOST-IF -m comment --comment "Unknown interface, return" -j RETURN
-A felix-from-30b4541c7ef -j MARK --set-xmark 0x0/0x1000000
-A felix-from-30b4541c7ef -m mac ! --mac-source 12:B9:A1:C4:73:0A -m comment --comment "Incorrect source MAC" -j DROP
-A felix-from-30b4541c7ef -m comment --comment "Start of tier default" -j MARK --set-xmark 0x0/0x2000000
-A felix-from-30b4541c7ef -m mark --mark 0x0/0x2000000 -j felix-p-_722590149132d26-o
-A felix-from-30b4541c7ef -m mark --mark 0x1000000/0x1000000 -m comment --comment "Return if policy accepted" -j RETURN
-A felix-from-30b4541c7ef -m mark --mark 0x0/0x2000000 -m comment --comment "Drop if no policy in tier passed" -j DROP
-A felix-from-30b4541c7ef -j felix-p-_0f05888047b5982-o
-A felix-from-30b4541c7ef -m mark --mark 0x1000000/0x1000000 -m comment --comment "Profile accepted packet" -j RETURN
-A felix-from-30b4541c7ef -m comment --comment "Packet did not match any profile (endpoint eth0)" -j DROP
-A felix-from-91f18ff5595 -j MARK --set-xmark 0x0/0x1000000
-A felix-from-91f18ff5595 -m mac ! --mac-source BE:D7:1F:94:45:42 -m comment --comment "Incorrect source MAC" -j DROP
-A felix-from-91f18ff5595 -m comment --comment "Start of tier default" -j MARK --set-xmark 0x0/0x2000000
-A felix-from-91f18ff5595 -m mark --mark 0x0/0x2000000 -j felix-p-_4c334da82b4ce35-o
-A felix-from-91f18ff5595 -m mark --mark 0x1000000/0x1000000 -m comment --comment "Return if policy accepted" -j RETURN
-A felix-from-91f18ff5595 -m mark --mark 0x0/0x2000000 -j felix-p-_258af862421b4a4-o
-A felix-from-91f18ff5595 -m mark --mark 0x1000000/0x1000000 -m comment --comment "Return if policy accepted" -j RETURN
-A felix-from-91f18ff5595 -m mark --mark 0x0/0x2000000 -j felix-p-_722590149132d26-o
-A felix-from-91f18ff5595 -m mark --mark 0x1000000/0x1000000 -m comment --comment "Return if policy accepted" -j RETURN
-A felix-from-91f18ff5595 -m mark --mark 0x0/0x2000000 -m comment --comment "Drop if no policy in tier passed" -j DROP
-A felix-from-91f18ff5595 -j felix-p-_43fdb4cd2c20923-o
-A felix-from-91f18ff5595 -m mark --mark 0x1000000/0x1000000 -m comment --comment "Profile accepted packet" -j RETURN
-A felix-from-91f18ff5595 -m comment --comment "Packet did not match any profile (endpoint eth0)" -j DROP
-A felix-from-c1f72ae9871 -j MARK --set-xmark 0x0/0x1000000
-A felix-from-c1f72ae9871 -m mac ! --mac-source 52:F4:BC:BA:ED:C1 -m comment --comment "Incorrect source MAC" -j DROP
-A felix-from-c1f72ae9871 -m comment --comment "Start of tier default" -j MARK --set-xmark 0x0/0x2000000
-A felix-from-c1f72ae9871 -m mark --mark 0x0/0x2000000 -j felix-p-_4c334da82b4ce35-o
-A felix-from-c1f72ae9871 -m mark --mark 0x1000000/0x1000000 -m comment --comment "Return if policy accepted" -j RETURN
-A felix-from-c1f72ae9871 -m mark --mark 0x0/0x2000000 -j felix-p-_258af862421b4a4-o
-A felix-from-c1f72ae9871 -m mark --mark 0x1000000/0x1000000 -m comment --comment "Return if policy accepted" -j RETURN
-A felix-from-c1f72ae9871 -m mark --mark 0x0/0x2000000 -j felix-p-_722590149132d26-o
-A felix-from-c1f72ae9871 -m mark --mark 0x1000000/0x1000000 -m comment --comment "Return if policy accepted" -j RETURN
-A felix-from-c1f72ae9871 -m mark --mark 0x0/0x2000000 -m comment --comment "Drop if no policy in tier passed" -j DROP
-A felix-from-c1f72ae9871 -j felix-p-_43fdb4cd2c20923-o
-A felix-from-c1f72ae9871 -m mark --mark 0x1000000/0x1000000 -m comment --comment "Profile accepted packet" -j RETURN
-A felix-from-c1f72ae9871 -m comment --comment "Packet did not match any profile (endpoint eth0)" -j DROP
-A felix-p-_0f05888047b5982-i -j MARK --set-xmark 0x1000000/0x1000000
-A felix-p-_0f05888047b5982-i -m mark --mark 0x1000000/0x1000000 -j RETURN
-A felix-p-_0f05888047b5982-o -j MARK --set-xmark 0x1000000/0x1000000
-A felix-p-_0f05888047b5982-o -m mark --mark 0x1000000/0x1000000 -j RETURN
-A felix-p-_258af862421b4a4-i -m set --match-set felix-4-s:uK4R6n61sYuSXSz0NO3eB src -j MARK --set-xmark 0x1000000/0x1000000
-A felix-p-_258af862421b4a4-i -m mark --mark 0x1000000/0x1000000 -j RETURN
-A felix-p-_258af862421b4a4-o -j MARK --set-xmark 0x1000000/0x1000000
-A felix-p-_258af862421b4a4-o -m mark --mark 0x1000000/0x1000000 -j RETURN
-A felix-p-_43fdb4cd2c20923-i -j MARK --set-xmark 0x1000000/0x1000000
-A felix-p-_43fdb4cd2c20923-i -m mark --mark 0x1000000/0x1000000 -j RETURN
-A felix-p-_43fdb4cd2c20923-o -j MARK --set-xmark 0x1000000/0x1000000
-A felix-p-_43fdb4cd2c20923-o -m mark --mark 0x1000000/0x1000000 -j RETURN
-A felix-p-_4c334da82b4ce35-o -m set --match-set felix-4-s:uK4R6n61sYuSXSz0NO3eB src -m set --match-set felix-4-s:dyxJvjPBmYbaQdqVo6EYi dst -j DROP
-A felix-p-_722590149132d26-i -j MARK --set-xmark 0x2000000/0x2000000
-A felix-p-_722590149132d26-i -m mark --mark 0x2000000/0x2000000 -j RETURN
-A felix-p-_722590149132d26-o -j MARK --set-xmark 0x2000000/0x2000000
-A felix-p-_722590149132d26-o -m mark --mark 0x2000000/0x2000000 -j RETURN
-A felix-to-30b4541c7ef -j MARK --set-xmark 0x0/0x1000000
-A felix-to-30b4541c7ef -m comment --comment "Start of tier default" -j MARK --set-xmark 0x0/0x2000000
-A felix-to-30b4541c7ef -m mark --mark 0x0/0x2000000 -j felix-p-_722590149132d26-i
-A felix-to-30b4541c7ef -m mark --mark 0x1000000/0x1000000 -m comment --comment "Return if policy accepted" -j RETURN
-A felix-to-30b4541c7ef -m mark --mark 0x0/0x2000000 -m comment --comment "Drop if no policy in tier passed" -j DROP
-A felix-to-30b4541c7ef -j felix-p-_0f05888047b5982-i
-A felix-to-30b4541c7ef -m mark --mark 0x1000000/0x1000000 -m comment --comment "Profile accepted packet" -j RETURN
-A felix-to-30b4541c7ef -m comment --comment "Packet did not match any profile (endpoint eth0)" -j DROP
-A felix-to-91f18ff5595 -j MARK --set-xmark 0x0/0x1000000
-A felix-to-91f18ff5595 -m comment --comment "Start of tier default" -j MARK --set-xmark 0x0/0x2000000
-A felix-to-91f18ff5595 -m mark --mark 0x0/0x2000000 -j felix-p-_4c334da82b4ce35-i
-A felix-to-91f18ff5595 -m mark --mark 0x1000000/0x1000000 -m comment --comment "Return if policy accepted" -j RETURN
-A felix-to-91f18ff5595 -m mark --mark 0x0/0x2000000 -j felix-p-_258af862421b4a4-i
-A felix-to-91f18ff5595 -m mark --mark 0x1000000/0x1000000 -m comment --comment "Return if policy accepted" -j RETURN
-A felix-to-91f18ff5595 -m mark --mark 0x0/0x2000000 -j felix-p-_722590149132d26-i
-A felix-to-91f18ff5595 -m mark --mark 0x1000000/0x1000000 -m comment --comment "Return if policy accepted" -j RETURN
-A felix-to-91f18ff5595 -m mark --mark 0x0/0x2000000 -m comment --comment "Drop if no policy in tier passed" -j DROP
-A felix-to-91f18ff5595 -j felix-p-_43fdb4cd2c20923-i
-A felix-to-91f18ff5595 -m mark --mark 0x1000000/0x1000000 -m comment --comment "Profile accepted packet" -j RETURN
-A felix-to-91f18ff5595 -m comment --comment "Packet did not match any profile (endpoint eth0)" -j DROP
-A felix-to-c1f72ae9871 -j MARK --set-xmark 0x0/0x1000000
-A felix-to-c1f72ae9871 -m comment --comment "Start of tier default" -j MARK --set-xmark 0x0/0x2000000
-A felix-to-c1f72ae9871 -m mark --mark 0x0/0x2000000 -j felix-p-_4c334da82b4ce35-i
-A felix-to-c1f72ae9871 -m mark --mark 0x1000000/0x1000000 -m comment --comment "Return if policy accepted" -j RETURN
-A felix-to-c1f72ae9871 -m mark --mark 0x0/0x2000000 -j felix-p-_258af862421b4a4-i
-A felix-to-c1f72ae9871 -m mark --mark 0x1000000/0x1000000 -m comment --comment "Return if policy accepted" -j RETURN
-A felix-to-c1f72ae9871 -m mark --mark 0x0/0x2000000 -j felix-p-_722590149132d26-i
-A felix-to-c1f72ae9871 -m mark --mark 0x1000000/0x1000000 -m comment --comment "Return if policy accepted" -j RETURN
-A felix-to-c1f72ae9871 -m mark --mark 0x0/0x2000000 -m comment --comment "Drop if no policy in tier passed" -j DROP
-A felix-to-c1f72ae9871 -j felix-p-_43fdb4cd2c20923-i
-A felix-to-c1f72ae9871 -m mark --mark 0x1000000/0x1000000 -m comment --comment "Profile accepted packet" -j RETURN
-A felix-to-c1f72ae9871 -m comment --comment "Packet did not match any profile (endpoint eth0)" -j DROP
```

**Comment by caseydavenport** [comment]
It does seem like it should be working, from my read of the above rules:

```
-A felix-to-c1f72ae9871 -m comment --comment "Start of tier default" -j MARK --set-xmark 0x0/0x2000000
-A felix-to-c1f72ae9871 -m mark --mark 0x0/0x2000000 -j felix-p-_4c334da82b4ce35-i
-A felix-to-c1f72ae9871 -m mark --mark 0x1000000/0x1000000 -m comment --comment "Return if policy accepted" -j RETURN
-A felix-to-c1f72ae9871 -m mark --mark 0x0/0x2000000 -j felix-p-_258af862421b4a4-i
-A felix-to-c1f72ae9871 -m mark --mark 0x1000000/0x1000000 -m comment --comment "Return if policy accepted" -j RETURN
-A felix-to-c1f72ae9871 -m mark --mark 0x0/0x2000000 -j felix-p-_722590149132d26-i
-A felix-to-c1f72ae9871 -m mark --mark 0x1000000/0x1000000 -m comment --comment "Return if policy accepted" -j RETURN
-A felix-to-c1f72ae9871 -m mark --mark 0x0/0x2000000 -m comment --comment "Drop if no policy in tier passed" -j DROP
```

I do notice that the policies include an explicit RETURN though.

```
-A felix-p-_258af862421b4a4-i -m set --match-set felix-4-s:uK4R6n61sYuSXSz0NO3eB src -j MARK --set-xmark 0x1000000/0x1000000
-A felix-p-_258af862421b4a4-i -m mark --mark 0x1000000/0x1000000 -j RETURN
```

But the first policy in the list doesn't.  Not sure if that is relevant...

**Comment by fasaxc** [comment]
> I do notice that the policies include an explicit RETURN though.

That's a conditional return; it's matching on the mark we set as the action of the rule above.  Setting the mark is how we set the "return code" of a chain so that we can represent "allow", "pass" and "didn't match" differently.

**Comment by fasaxc** [comment]
OK, I think I've managed to repro this issue.  I think the problem is that your egress rule is too aggressive in what it drops.  In particular, I had to add an egress allow rule that allowed DNS lookups.

Diagnosed by watching the packet counters of drop rules on the host of my test busybox pod to see what was being hit:
```
sudo watch -n 0.5 -d 'iptables -L -v | grep DROP'
```

**Comment by fasaxc** [comment]
This was the policy that I used (with the simple policy demo NGINX set-up):
```
- apiVersion: v1
  kind: policy
  metadata:
    name: egress
  spec:
    egress:
    - action: allow
      protocol: udp
      destination:
        selector: calico/k8s_ns == 'kube-system' && k8s-app=='kube-dns'
        ports: 
        - 53
    - action: deny
      destination:
        notSelector: calico/k8s_ns == 'policy-demo'
    order: 999
    selector: calico/k8s_ns == 'policy-demo'
```

**Comment by caseydavenport** [comment]
@fasaxc yes, that was it.  I had forgotten to allow DNS :(

**Comment by caseydavenport** [comment]
I wanted to re-open this discussion because I think this is confusing behavior for users.

The way Calico works now, default behavior for ingress changes as soon as the first egress policy is created, and vice-versa. 

Basically, when I apply this policy: 

```
- apiVersion: v1
  kind: policy
  metadata:
    name: allow-from-clients
  spec:
    selector: role == 'server'
    ingress:
    - action: allow
      source:
        selector: role == 'client'
    order: 500
```

Suddenly my `role == 'server'` pods can no longer talk to _anything_, which is really confusing and not particularly easy to spot.

Maybe this is just a documentation issue that we need to make REALLY clear, or maybe we need to re-think the interaction here.  I think it's crucial that the policy model is intuitive. 

CC @lxpollitt @gunjan5
