### ISSUE TITLE
New pod with UDP hostPort fails to clear existing conntrack sessions

### ISSUE THREAD

**Issue by brantburnett** [projectcalico/felix#1880]
When a new pod is launched with a UDP hostPort, conntrack sessions remain active when flow traffic to the host IP rather than the pod IP.  Because UDP is stateless, but NAT is not, this can create a black hole for UDP traffic.  The UDP consumer expects all new packets to go to the pod.  However, so long as the session continues to receive traffic which resets the session timeout, it will continue to be routed to the host IP instead of the pod IP.

## Expected Behavior
Once a new pod is launched with a UDP hostPort, all UDP traffic to the host IP/port tuple should be forwarded to the pod immediately.

## Current Behavior
Any UDP traffic to the host IP/port tuple which was received by the host before the pod is launched creates a session.  So long as the same source IP/port tuple sends UDP traffic regularly (< every 30 seconds) those packets will be lost indefinitely.  Because UDP is stateless, the source has no way to know the packets weren't delivered to the pod as expected.

## Possible Solution
When a pod is launched with a UDP hostPort, use conntrack to delete any UDP sessions with the host IP/port tuple as the destination.  This will allow new sessions to be started with the pod IP/port tuple as the destination.  This must be done after IPTABLES are updated for the new pod so new sessions routed to the host IP aren't created between the two steps.

## Steps to Reproduce (for bugs)
1. `kubectl create ns test`
2. `kubectl label node <node> test=test` This allows us to use a node selector to put two pods on the same node.
3. Save this file as `dest.yaml`

    ```yaml
    kind: Pod
    apiVersion: v1
    metadata:
      name: dest
      namespace: test
    spec:
      containers:
      - image: subfuzion/netcat
        name: dest
        args:
        - "-kluw"
        - "0"
        - "6000"
        ports:
        - containerPort: 6000
          hostPort: 6000
          name: destport
          protocol: UDP
      nodeSelector:
          test: test
    ```

4. `kubectl apply -f dest.yaml`
5. Save this file as `source.yaml`

    ```yaml
    kind: Pod
    apiVersion: v1
    metadata:
      name: source
      namespace: test
    spec:
      containers:
      - image: subfuzion/netcat
        name: source
        command:
        - /bin/sh
        args:
        - "-c"
        - "for i in `seq 1 1000`; do echo \"test!\" | nc -u -p 40001 -w 1 $HOSTIP 6000; sleep 2; done"
        env:
        - name: HOSTIP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
      nodeSelector:
        test: test
    ```

6. `kubectl apply -f source.yaml`
7. `kubectl -n test logs dest` and observe that you see "test!" repeating every 3 seconds
8. `kubectl delete -f ./dest.yaml` and wait 30 seconds for pod to terminate
9. At this point, if you directly access the K8S node you can see a conntrack session with the destination being the host IP, with the TTL continuing to stay near 30 seconds
10. `kubectl apply -f ./dest.yaml`
11. `kubectl -n test logs dest` note that you won't see any "test!" repeating
12. Note that conntrack session on the node still exists, still going to the host IP
13. `kubectl delete -f ./source.yaml` and wait 30 seconds for the pod to terminate
14. `kubectl apply -f ./source.yaml`
15. `kubectl -n test logs dest` and observe that you see "test!" repeating every 3 seconds
16. Note that conntrack session on the node now points to the pod IP

## Context
An example case that triggers this problem is a StatsD agent running in a DaemonSet.  Application pods sending UDP statistics to the pod via the host IP tend to send traffic constantly and from the same source port number (for socket allocation efficiency).  If the agent pod is killed and a replacement pod launched on the same node, all stats UDP packets begin going nowhere until each application pod is recycled.  See https://github.com/DataDog/dogstatsd-csharp-client/issues/64.

## Your Environment
- quay.io/calico/node:v2.6.7
- Kubernetes 1.9.3
- gcr.io/google_containers/etcd:2.2.1
- kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08 (AWS AMI)
- All deployed using Kops 1.9.0

**Comment by fasaxc** [comment]
@caseydavenport Is Calico involved in implementing host ports?  I'd have expected them to be set up by kube-proxy or kubelet.

**Comment by tmjd** [comment]
@fasaxc I believe you are correct that they are set up by kube-proxy.
@brantburnett Is there a specific reason you think this is a Calico issue?
Here are some K8s github issues that I  think are related:
- https://github.com/kubernetes/kubernetes/issues/65228
- https://github.com/kubernetes/kubernetes/issues/66651

**Comment by brantburnett** [comment]
@tmjd 

I admit, the idea that it was a Calico issue was an assumption.  I tried digging around on the internet and found references to hostPort being implemented by CNI plugins, so I assumed it was Calico's responsibility.  However, I didn't ever find clear documentation one way or the other.

If Calico isn't handling hostPort IPTABLE entries, then I would agree this isn't a Calico issue.  However, if Calico is creating the IPTABLE entries for hostPort, I would saying clearing conntrack would be a Calico issue, especially considering that clearing other conntrack sessions is something Calico is doing currently.

**Comment by fasaxc** [comment]
@brantburnett what's in your CNI config file in /etc/cni/net.d?

**Comment by brantburnett** [comment]
@fasaxc 

From /etc/cni/net.d on one of the nodes:

calico-kubeconfig:
```yaml
# Kubeconfig file for Calico CNI plugin.
apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    insecure-skip-tls-verify: true
users:
- name: calico
contexts:
- name: calico-context
  context:
    cluster: local
    user: calico
current-context: calico-context
```
10-calico.conflist:
```json
{
  "name": "k8s-pod-network",
  "cniVersion": "0.3.0",
  "plugins": [
    {
      "type": "calico",
      "etcd_endpoints": "http://etcd-a.internal.k8s.<redacted>:4001,http://etcd-d.internal.k8s.<redacted>:4001,http://etcd-f.internal.k8s.<redacted>:4001",
      "log_level": "info",
      "ipam": {
        "type": "calico-ipam"
      },
      "policy": {
        "type": "k8s",
        "k8s_api_root": "https://100.64.0.1:443",
        "k8s_auth_token": "<redacted>"
      },
      "kubernetes": {
        "kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
      }
    },
    {
      "type": "portmap",
      "snat": true,
      "capabilities": {"portMappings": true}
    }
  ]
}
```
