### ISSUE TITLE
Felix 2.x not support networkpolicy namespace with pod selector 

### ISSUE THREAD

**Issue by BSWANG** [projectcalico/felix#1947]
When using k8s network policy which combined namespace and pod label selector. The network policy will block whole namespace, even match pod label selector. 
## Expected Behavior

Don't block pod which networkpolicy selected.

## Current Behavior

Block whole namespace of pod which networkpolicy selected.

## Possible Solution

None.

## Steps to Reproduce (for bugs)

1. deploy a nginx deploy as test server and get the server IP.

```
kubectl run --labels run=nginx --image nginx nginx
kubectl get pod -o wide
NAME                     READY   STATUS    RESTARTS   AGE     IP                NODE                      NOMINATED NODE   READINESS GATES
nginx-7cdbd8cdc9-8427c   1/1     Running   0          6m58s   192.168.107.131   izj6cb3rv931tlpckje0i3z   <none>           <none>
```
2. create and label a namespace for client

```
kubectl create ns test
kubectl label ns test ns=test
```
3. create network policy cr
```
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  name: network-policy-1848-001
  namespace: default
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          ns: test
      podSelector:
        matchLabels:
          access: test
  podSelector:
    matchLabels:
      run: nginx
  policyTypes:
  - Ingress
```
4. Deploy test client and test connection
```
# #This pod should be accessable to server, but timeout.
# kubectl --namespace test run -it --rm --labels access=test --image busybox busybox
/ # wget -O- 192.168.107.131
Connecting to 192.168.107.131 (192.168.107.131:80)
wget: can't connect to remote host (192.168.107.131): Connection timed out

# kubectl --namespace test run -it --rm --labels access1=test1 --image busybox busybox2
/ # wget -O- 192.168.107.131
Connecting to 192.168.107.131 (192.168.107.131:80)
wget: can't connect to remote host (192.168.107.131): Connection timed out
```

## Context

I use the network policy combined namespace and pod to set accessable between `ingress pod in kube-system` and production namespaces and pod.

## Your Environment

* Felix version (if using Felix binary directly `calico-felix --version`):  2.6.8
* And/Or, `calico/node` container version (if running Felix in a container): v2.6.12
* Which orchestrator are you using (e.g. Kubernetes, OpenStack, Docker, Mesos): Kubernetes
* Orchestrator version (if used): 1.13
* Etcd version (if using etcd datastore driver): v3.1.10
* Operating System and version: Centos 7.4
* Link to your project (optional):
