### ISSUE TITLE
Compatibility issue with k8s pod container postStart hook

### ISSUE THREAD

**Issue by BSWANG** [projectcalico/felix#2008]
I create an pod with postStart hook `curl xxx.com`. eg:

```
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busybox
    image: registry.aliyuncs.com/wangbs/netdia
    command:
    - sh
    - -c
    - "sleep 400000"
    lifecycle:
      postStart:
        exec:
          command:
          - curl
          - google.com
```
During the postStart `curl` execution, the pod status is `ContainerCreating`. `Felix` will not config `network policy` rules in iptables. Thus the postStart `curl` will timeout and fail. This pod going into deadlock situation.

## Expected Behavior

Felix should config `network policy` rule on pod `ContainerCreating` status.

## Current Behavior

Felix doesn't config `network policy` rule on pod `ContainerCreating` status.

## Possible Solution

Felix should config `network policy` rule on pod `ContainerCreating` status.

## Steps to Reproduce (for bugs)

1. Create pod like before description
2. Watch pod status.

## Context

My `TaskWorker` pod use the `postStart` hook to remote notify the `TaskMaster` to dispatch tasks.

## Your Environment

* Felix version (if using Felix binary directly `calico-felix --version`):  v3.5.2
* And/Or, `calico/node` container version (if running Felix in a container): Only use felix alone for policy.
* Which orchestrator are you using (e.g. Kubernetes, OpenStack, Docker, Mesos): Kubernetes
* Orchestrator version (if used): 1.12.6
* Operating System and version: Centos 7.6
