### ISSUE TITLE
Fail to contact public endpoint during postStart lifecycle hook

### ISSUE THREAD

**Issue by thelo-gaultier** [projectcalico/felix#2134]
I create a pod with a podStart lifecycle hook that should fetch some content on the internet

```
apiVersion: v1
kind: Pod
metadata:
  name: test-calico-post-start
spec:
  containers:
  - name: test-calico
    image: byrnedo/alpine-curl:latest
    command:
    - sh
    - -c
    - "sleep 400000"
    lifecycle:
      postStart:
        exec:
          command: [ "/bin/sh","-c","result=$(curl  http://www.google.com 1> /var/log/output.log 2> /var/log/output-error.log ); echo $result"]
```

Here the return code is store into a variable just not to fail when the curl command fails.

## Expected Behavior
The ```curl``` command should succeed and properly get ```http://www.google.com``` webpage

## Current Behavior
During the postStart hook, the pod has the status ```containerCreating```, it appears that during that status the pod cannot reach out to the internet

As we forward stderr to the ```output-error.log``` file, we can see that the ```curl``` command fails with the following message
```
~ $ kubeclt exec -it test-calico-post-start -- cat /var/log/output-error.log
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0curl: (6) Could not resolve host: www.google.com
```

Once the pod status is on ```running```, then the domain name resolution works properly
```
~ $ k exec -it test-calico-post-start -- ping google.com
PING google.com (216.58.211.142): 56 data bytes
64 bytes from 216.58.211.142: seq=0 ttl=49 time=3.438 ms
64 bytes from 216.58.211.142: seq=1 ttl=49 time=3.291 ms
64 bytes from 216.58.211.142: seq=2 ttl=49 time=3.320 ms
```

If I remove Calico then rotate my nodes, the postStart hook script can resolve ```www.google.com``` properly

## Steps to Reproduce (for bugs)

1. Install Calico : ( source : https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/master/config/v1.5/calico.yaml )
2. Run the manifest described above
3. Once the pod is in running mode, you can check the stderr output of the curl command 
``` kubectl exec -it test-calico-post-start -- cat /var/log/output-error.log```

## Context
Here, we are trying to download a file from S3 at start up time on the container. 

## Your Environment
The entire calico manifest can be found here : https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/master/config/v1.5/calico.yaml

* Felix version : v3.8.1
* And/Or, `calico/node` container version (if running Felix in a container):
* Which orchestrator are you using: Kubernetes managed by AWS
* Orchestrator version (if used): v1.13.8-eks-a977ba
* CNI : amazon-vpc-cni-k8s v1.5.3
* Operating System and version: alpine
