### ISSUE TITLE
More information on output of Calico action Log

### ISSUE THREAD

**Issue by rafagsiqueira** [projectcalico/felix#2163]
To use a safe approach I am trying to start with a deny all network policy. I want it to first log the denied packages and then deny them.
It sounds very stupid but I can't find the Logged denied packages anywhere. I have tried looking on the logs of the calico containers. I have tried exec'ing inside the container and their /var/log folder is also empty. I believe this is probably very straight-forward, but I can't seem to find it.

Here is the policy I have applied.
```
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: dev
spec:
  selector: all()
  types:
  - Ingress
  - Egress
  ingress:
  - action: Log
  - action: Deny
  egress:
  - action: Log
  - action: Deny
```
