### ISSUE TITLE
Cross namespace deny policy, can still access service in another namespace

### ISSUE THREAD

**Issue by dave-meier** [projectcalico/felix#2625]
Posting this here as well, submitted https://github.com/projectcalico/calico/issues/4078

In EKS, I have 1 linux master node and 2 windows server core non-managed nodes.

I am stuck on this, and looking for any advice or things to try that anyone has. Where I'm at now is just trying to prevent cross namespace traffic, but have 2 problems:

- I can still call a service from a container in a different namespace.
- From the Target Server in AWS, the node where my service pod is not running fails connectivity tests. The node where the service pod is running passes connectivity tests.

NetworkPolicy:
```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: green
  name: deny-traffic-other-namespaces
spec:
  podSelector:
    matchLabels:
  ingress:
  - from:
    - podSelector: {}
```
